"""add_service_planning_assignment_models

Revision ID: 076396980932
Revises: 0ec1aa542677
Create Date: 2025-12-27 21:34:02.364594

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "076396980932"
down_revision: str | None = "0ec1aa542677"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plannings",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("department_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "GENERATED", "PUBLISHED", "ARCHIVED", name="planning_status"
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("department_id", "month", name="uq_plannings_dept_month"),
    )
    op.create_index(
        "ix_plannings_department_id", "plannings", ["department_id"], unique=False
    )
    op.create_index(
        "ix_plannings_organization_id", "plannings", ["organization_id"], unique=False
    )
    op.create_table(
        "services",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("department_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("service_type", sa.String(length=100), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("dress_code_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "required_roles", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("recurrence_rule", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_services_date", "services", ["date"], unique=False)
    op.create_index(
        "ix_services_department_date",
        "services",
        ["department_id", "date"],
        unique=False,
    )
    op.create_index(
        "ix_services_department_id", "services", ["department_id"], unique=False
    )
    op.create_index(
        "ix_services_organization_id", "services", ["organization_id"], unique=False
    )
    op.create_table(
        "planning_assignments",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("planning_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("service_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("member_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("assigned_role", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ASSIGNED",
                "CONFIRMED",
                "DECLINED",
                "REPLACED",
                name="assignment_status",
            ),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["planning_id"], ["plannings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "service_id", "member_id", name="uq_assignments_service_member"
        ),
    )
    op.create_index(
        "ix_planning_assignments_member_id",
        "planning_assignments",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        "ix_planning_assignments_organization_id",
        "planning_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_planning_assignments_planning_id",
        "planning_assignments",
        ["planning_id"],
        unique=False,
    )
    op.create_index(
        "ix_planning_assignments_service_id",
        "planning_assignments",
        ["service_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_planning_assignments_service_id", table_name="planning_assignments"
    )
    op.drop_index(
        "ix_planning_assignments_planning_id", table_name="planning_assignments"
    )
    op.drop_index(
        "ix_planning_assignments_organization_id", table_name="planning_assignments"
    )
    op.drop_index(
        "ix_planning_assignments_member_id", table_name="planning_assignments"
    )
    op.drop_table("planning_assignments")
    op.drop_index("ix_services_organization_id", table_name="services")
    op.drop_index("ix_services_department_id", table_name="services")
    op.drop_index("ix_services_department_date", table_name="services")
    op.drop_index("ix_services_date", table_name="services")
    op.drop_table("services")
    op.drop_index("ix_plannings_organization_id", table_name="plannings")
    op.drop_index("ix_plannings_department_id", table_name="plannings")
    op.drop_table("plannings")
    # ### end Alembic commands ###
