"""add_department_member_availability_tables

Revision ID: 6b6da3eebbcd
Revises: 01ce92d51b38
Create Date: 2025-12-27 20:59:41.773352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b6da3eebbcd"
down_revision: Union[str, None] = "01ce92d51b38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("settings", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("availability_deadline_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_departments_org_name"),
    )
    op.create_index(
        "ix_departments_organization_id",
        "departments",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "members",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("department_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MANAGER", "MEMBER", name="member_role"),
            nullable=False,
        ),
        sa.Column("skills", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACTIVE", "INACTIVE", name="member_status"),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("department_id", "user_id", name="uq_members_dept_user"),
    )
    op.create_index(
        "ix_members_department_id", "members", ["department_id"], unique=False
    )
    op.create_index(
        "ix_members_organization_id", "members", ["organization_id"], unique=False
    )
    op.create_index("ix_members_user_id", "members", ["user_id"], unique=False)
    op.create_table(
        "availabilities",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("member_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("is_all_day", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "date", name="uq_availabilities_member_date"),
    )
    op.create_index(
        "ix_availabilities_member_date",
        "availabilities",
        ["member_id", "date"],
        unique=False,
    )
    op.create_index(
        "ix_availabilities_member_id", "availabilities", ["member_id"], unique=False
    )
    op.create_index(
        "ix_availabilities_organization_id",
        "availabilities",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_availabilities_organization_id", table_name="availabilities")
    op.drop_index("ix_availabilities_member_id", table_name="availabilities")
    op.drop_index("ix_availabilities_member_date", table_name="availabilities")
    op.drop_table("availabilities")
    op.drop_index("ix_members_user_id", table_name="members")
    op.drop_index("ix_members_organization_id", table_name="members")
    op.drop_index("ix_members_department_id", table_name="members")
    op.drop_table("members")
    op.drop_index("ix_departments_organization_id", table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
